config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
	member do 
		get "like", to:"posts#upvote"
		get "dislike", to:"posts#downvote"
	end
	resources :comments
  end
  root 'posts#index'
  
  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments, :dependent => :destroy
  mount_uploader :image, ImageUploader
  
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:posts
  has_many:comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
	  devise_parameter_sanitizer.permit(:account_update, keys:[:name])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.post_id = @post.id

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
 
		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy upvote downvote]
  before_action :authenticate_user!, expect:[:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1 or /posts/1.json
  def show
	@comments = Comment.where(post_id: @post)
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    
    end
  end

	def upvote
		@post.upvote_by current_user
		redirect_back fallback_location: posts_path
	end

	def downvote
		@post.downvote_from current_user
		redirect_back fallback_location: posts_path
	end
	
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :link, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
        <p class="comment_content"><%= comment.user.name %></p>       
		<p class="comment_content"><%= comment.content %></p>
		
	</div>

	<% if user_signed_in? %>
		<p><%= link_to 'Delete', [comment.post, comment],
			method: :delete,
			class: "button",
			data: { confirm: 'Are you sure?' } %>
               </p>
 	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.text_field  :content, label: "Reply to thread" %>
	<%= f.button :submit, class: "button" %>



<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo.svg" %>
			<% end %>
		</div>

		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="http://www.paulhsiung.com/">Blog</a></li>
			<li><a href="https://www.facebook.com/profile.php?id=100000247759716">Facebook</a></li>
			<li><a href="https://github.com/paul12999">Github</a></li>
			<li><a href="">Email</a></li>
		</ul>
		
		<% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
		<% end %>
		
	</div>
	<div id="main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>

			<% if user_signed_in? %>
				<div class="buttons">
					<button class="button"><%= link_to "New Post", new_post_path %></button>
					<button class="button"><%= link_to "登出" , destroy_user_session_path , :method => 'delete'  %></button>
				</div>
			<% end %>
		</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>
	</div>
    
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "about.jpg" %>
	</div>

	<div id="content">
		<h1>Hey, I'm Hsiung Paul</h1>
		<p>您好，我是熊伯洋 ，畢業於國立中正大學通訊工程所網路組，大學就讀元智大學通訊工程學系。研究所研究網路安全相關領域，畢業論文是基於霧計算架構之行動共謀攻擊偵測機制，主要是雲端計算與手機安全結合，目的是減少手機傳輸資料量及偵測所消耗能量。</p>

		<p>經過一年的時間，已經完全handle這分工作，決定想轉行成前後端工程師，自修三個月架設網頁和後端基礎，目前研讀後端方面的工具，目標成為全端工程師。</p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html (copy).erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to (image_tag post.image.url(:small)), post %></td>
        <td><%= link_to post.title, post %></td>
        <td><%= post.link %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/index.html.haml
- if user_signed_in?
	%p#intro
		Hello
		= current_user.name
		%br/
		%span
			Share your inspiration and see what's inspiring others.
- else
	%p#intro
		What's your muse?
		%br/
		%span
			Share your inspiration and see what's inspiring others.
#posts
	- @posts.each do |post|
		.post
			.post_image
				= link_to (image_tag post.image.url , class: "image-small" ), post
			.post_content
				.title
					%h2= link_to post.title, post
				.data.clearfix
					%p.username
						Shared by
						= post.user.name
					%p.buttons
						%span
							%i.fa.fa-comments-o
							= post.comments.count
						%span
							%i.fa.fa-thumbs-o-up
							= post.get_likes.size

= link_to 'New Post', new_post_path 

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html (copy).erb
<p id="notice"><%= notice %></p>
<%= image_tag @post.image.url(:small) %>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @post.link %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

#comments
<%= comment_count= pluralize(@post.comments.count, "Comment") %>
	<%= @comments.each do |comment| %>
		.comment
		
			<%= p.content= comment.content %>
    <% end %>
	<%= render "comments/form" %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<%= link_to 'Home', root_path %>

app/views/posts/show.html.haml
#post_show
	%h1= @post.title
	%p.username
		Shared by
		= @post.user.name
		about
		= time_ago_in_words(@post.created_at)
	.clearfix
		.post_image_description
			= image_tag @post.image.url , class: "image-big" 
			.description= simple_format(@post.description)
		.post_data

			= link_to like_post_path(@post), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-up
				= pluralize(@post.get_upvotes.size, "Like")
			= link_to dislike_post_path(@post), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-down
				= pluralize(@post.get_downvotes.size, "Dislike")
			%p.data
				%i.fa.fa-comments-o
				= pluralize(@post.comments.count, "Comment")
			- if @post.user == current_user
				= link_to "Edit", edit_post_path(@post), class: "data"
				= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "data"
				= link_to "Home", root_path(@post), class: "data"


#comments
	%h2.comment_count= pluralize(@post.comments.count, "Comment")

	
			
	= render @post.comments 
	= render "comments/form"
	